### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZuoxiYang** [SungMinCho/MEANTIME#1]
Hi, when I ran the command "python run.py --templates train_meantime --mode test --pretrained_weights path/to/weights", it reported an error as follows:
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    main()
  File "/MEANTIME/meantime/main.py", line 16, in main
    training_main(args)
  File "/MEANTIME/meantime/top/training.py", line 14, in main
    validate(args, mode='test')
  File "/MEANTIME/meantime/top/training.py", line 56, in validate
    local_export_root, remote_export_root, communicator = setup_train(args, MACHINE_IS_HOST)
  File "/MEANTIME/meantime/utils.py", line 51, in setup_train
    remote_export_root = os.path.join(REMOTE_ROOT, local_export_root)
  File "/.conda/envs/tf/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

so are there any roots that need to be set? How to set them correctly? Thanks for your answer.

**Comment by SungMinCho** [comment]
Hello. Thanks for your interest.

Two things:

1.
There was a bug in the code.
By default, REMOTE_ROOT is None, and remote_export_root shouldn't be created when MACHINE_IS_HOST flag is on.
I pushed a fix so it's going to work fine.

2.
However, you shouldn't run like this: `python run.py --templates train_meantime --mode test --pretrained_weights path/to/weights`

Because `path/to/weights` was just written symbolically.
In reality, you should specify the actual path to the model file.
For example, if your train results are saved in `experiments/test/meantime`,
then there will be model weight files in `experiments/test/meantime/models`.
You can pick one of them and use it for inference.
For example:
`python run.py --templates train_meantime --mode test --pretrained_weights experiments/test/meantime/models/best_model.pth`

Thank you!

**Comment by ZuoxiYang** [comment]
> Hello. Thanks for your interest.
> 
> Two things:
> 
> 
> There was a bug in the code.
> By default, REMOTE_ROOT is None, and remote_export_root shouldn't be created when MACHINE_IS_HOST flag is on.
> I pushed a fix so it's going to work fine.
> 
> 
> However, you shouldn't run like this: `python run.py --templates train_meantime --mode test --pretrained_weights path/to/weights`
> 
> Because `path/to/weights` was just written symbolically.
> In reality, you should specify the actual path to the model file.
> For example, if your train results are saved in `experiments/test/meantime`,
> then there will be model weight files in `experiments/test/meantime/models`.
> You can pick one of them and use it for inference.
> For example:
> `python run.py --templates train_meantime --mode test --pretrained_weights experiments/test/meantime/models/best_model.pth`
> 
> Thank you!

Thanks for your answer. And will more baseline models (or other sequential models) be added in this repository?

**Comment by SungMinCho** [comment]
That would really be worthwhile but unfortunately I don't have any plans for now. Thanks.

**Comment by ZuoxiYang** [comment]
Hi, when I ran the command: "python run.py --templates train_marank --test_negative_sampler_code=random", it reported an error as follows:

]Traceback (most recent call last):
  File "run.py", line 5, in <module>
    main()
  File "./meantime/main.py", line 18, in main
    training_main(args)
  File "./meantime/top/training.py", line 10, in main
    train(args)
  File "./meantime/top/training.py", line 31, in train
    trainer.train()
  File "./meantime/trainers/base.py", line 96, in train
    accum_iter = self.train_one_epoch(epoch, accum_iter, self.train_loader)
  File "./meantime/trainers/base.py", line 136, in train_one_epoch
    for batch_idx, batch in enumerate(tqdm_dataloader):
  File "./.conda/envs/tf/lib/python3.6/site-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "./.conda/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "./.conda/envs/tf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./.conda/envs/tf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./meantime/dataloaders/sas.py", line 78, in __getitem__
    negative_labels = [self.rng.choice(neg_samples)]
  File "./.conda/envs/tf/lib/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

Have you ever encountered this problem and how to solve it?
